// Single source for term definitions: Place Lab modals and methods.html read the same entries.
// Keys are stable anchors (methods.html#term-<key>); edit wording here, not in either page.
export const CATEGORIES={
  measure:'ZIP measures',
  projection:'Project comparison',
  text:'Text analysis',
  model:'Modeling and evaluation',
  geography:'Geography and sources'
};

export const GLOSSARY={
  engagement:{term:'Business engagement',category:'measure',
    definition:'How often people review local businesses in an area, counted as Yelp reviews per square kilometer per year. We use it as a stand-in for how much customers engage with nearby businesses.',
    formula:'Reviews in 2019–2021 ÷ 3 years ÷ ZIP area in km²',
    caution:'Counts written reviews only. Visits, sales and revenue are out of reach. Needs at least 100 reviews in the period. ZIP area includes water.'},
  engagement_change:{term:'Change in business engagement',category:'measure',
    definition:'Percent change in Yelp reviews between two three-year windows.',
    formula:'100 × (reviews 2019–2021 ÷ reviews 2012–2014 − 1)',
    caution:'Both windows need at least 100 reviews. The later window includes COVID-19. More or fewer reviews does not tell you businesses opened or closed.'},
  listings:{term:'Yelp listings',category:'measure',
    definition:'Businesses in the Yelp Open Dataset whose coordinates fall in the ZIP.',
    caution:'A January 2022 archive. Plenty of current businesses are missing.'},
  reviews:{term:'Reviews',category:'measure',
    definition:'Count of Yelp reviews written for businesses in the ZIP during 2019–2021.'},
  sentiment:{term:'Average review sentiment',category:'measure',
    definition:'Mean VADER compound score of review text, from −1 for most negative to +1 for most positive.',
    formula:'Sum of review compound scores ÷ number of reviews',
    caution:'Scores the whole review, and most reviews are about the business.'},
  sentiment_vs_metro:{term:'Sentiment change vs. rest of metro',category:'measure',
    definition:'How much the ZIP\'s average sentiment changed between 2012–2014 and 2019–2021, minus the change across the rest of its metro.',
    formula:'(ZIP late − ZIP early) − (rest-of-metro late − rest-of-metro early)',
    caution:'The value can be positive even when the ZIP\'s own sentiment fell, if the metro fell further.'},
  access_discussion:{term:'Access & parking discussion',category:'measure',
    definition:'Share of 2019–2021 reviews that mention parking, walking, transit or accessibility.',
    formula:'100 × reviews with an access keyword ÷ all reviews',
    caution:'Counts praise and complaints alike, so a high rate does not mean people are unhappy.'},
  income:{term:'Median household income',category:'measure',
    definition:'The American Community Survey five-year estimate of median household income for the ZCTA, in nominal dollars, with its published margin of error.',
    caution:'Covers 2007–2011 for Philadelphia and Tucson and 2008–2012 elsewhere. It describes residents. Yelp reviewers may live anywhere.'},
  poverty:{term:'Population below poverty',category:'measure',
    definition:'The ACS five-year estimate of the share of people, among those with a known poverty status, living below the federal poverty line.',
    caution:'Same periods as income. These are historical figures and may not match today.'},
  area:{term:'Land and water area',category:'measure',
    definition:'Area of the ZIP Code Tabulation Area polygon, measured on a sphere with holes subtracted.',
    caution:'Includes water, which lowers per-km² engagement for waterfront ZIPs.'},
  city_median:{term:'City median',category:'measure',
    definition:'The middle value of the measure across mapped ZIPs in the same metro that have data.'},
  city_rank:{term:'City rank',category:'measure',
    definition:'Where the ZIP falls among mapped ZIPs in its metro. 1 is the highest value. ZIPs with limited data get no rank.'},
  limited_data:{term:'Limited data',category:'measure',
    definition:'The ZIP fell short of the minimum for this measure, usually 100 reviews per period, or the source had no estimate.',
    caution:'Limited data is not zero.'},

  project_family:{term:'Project family',category:'projection',
    definition:'Past projects grouped by kind: trail or greenway, waterfront park, civic park or plaza, and transit line. The eleven source projects each had their own type label, so we grouped them to compare like with like.'},
  near_area:{term:'Near area',category:'projection',
    definition:'Reviewed businesses within 500 meters of a past project\'s mapped footprint or center point.'},
  comparison_area:{term:'Comparison area',category:'projection',
    definition:'Reviewed businesses 1.5 to 8 km from the same project. They show the citywide trend that would have happened without the project.'},
  adjusted_change:{term:'Comparison-adjusted change',category:'projection',
    definition:'A difference-in-differences. Take the change near a project from the two years before opening to the two years after, then subtract the same change in its comparison area.',
    formula:'(near post − near pre) − (comparison post − comparison pre)',
    caution:'We compare engagement on a log scale, so read it as a percent difference in growth.'},
  family_average:{term:'Family average',category:'projection',
    definition:'The average comparison-adjusted change across past projects of one kind, or all ten, with a count of how many moved the better way. Engagement is averaged on a log scale, which makes it a geometric mean of growth ratios.',
    caution:'This summarizes a handful of places. Don\'t read it as the effect to expect. Family averages predicted held-out projects no better than the all-project average.'},
  range_in_family:{term:'Range in family',category:'projection',
    definition:'The lowest and highest comparison-adjusted change in the family, which shows how much projects of the same kind differed.'},
  negative_access:{term:'Negative access & parking mentions',category:'projection',
    definition:'Share of reviews with a negative clause about walking, transit or parking in the surrounding area.',
    caution:'Low reliability. On 514 labeled clauses, the keyword rules found about 1 in 6 negative area comments, with recall 0.16 and precision 0.39. So this rate undercounts complaints. The labels came from an AI annotator and still need a human recheck.'},
  negative_realm:{term:'Negative public-space mentions',category:'projection',
    definition:'Share of reviews with a negative clause about safety, cleanliness, public space, construction or the neighborhood around the business.',
    caution:'Low reliability, for the same reason as negative access mentions. The rules miss most of the negative area comments a reader would catch.'},
  loo_check:{term:'Leave-one-project-out check',category:'projection',
    definition:'We drop each project in turn, recompute its family estimate from the others and record the miss. Then we compare that error with the error of the plain all-project average.',
    caution:'Family estimates never beat the all-project average. Projects in the same family differ more than the families do.'},

  vader:{term:'VADER',category:'text',
    definition:'Valence Aware Dictionary and sEntiment Reasoner, a word-list and rule-based scorer built for short social-media text. It returns a compound score from −1 to +1 and handles negation, intensifiers and punctuation.',
    caution:'Nothing was trained. It is a lexical baseline, run with the vaderSentiment Python package.'},
  clause_rules:{term:'Clause-level topic rules',category:'text',
    definition:'We split reviews into clauses and tag nine topics with keyword patterns: walking, transit, parking, safety, cleanliness, public space, construction, food and service, and neighborhood. Each clause is then labeled as about the area or the business, and as positive, neutral or negative using VADER plus a list of complaint phrases.',
    caution:'Rule version place-clause-rules-v1. Checked against 731 agent-labeled items, the rules find about 1 in 6 negative area comments. See Checking the text measures on the methodology page.'},
  tfidf:{term:'TF-IDF',category:'text',
    definition:'Term frequency–inverse document frequency. Each review becomes weighted counts of words and two-word phrases, and words that show up in most reviews count for less.',
    formula:'Unigrams and bigrams, sublinear term frequency, English stop words, min document frequency 2, max 95%, 8,000 features'},
  nmf:{term:'Non-negative matrix factorization (NMF)',category:'text',
    definition:'An unsupervised topic model. It splits the TF-IDF matrix into five topics, each a weighted list of terms, and gives every review a mix of those topics.',
    caution:'Fit to 10,971 sampled reviews from before each opening. Most topics are about food and service.'},
  topic_diversity:{term:'Topic diversity',category:'text',
    definition:'Shannon entropy of a project\'s average topic mix, divided by log(5). Zero means one topic dominates. One means an even spread.'},

  capital_efficiency:{term:'Capital efficiency (CE)',category:'model',
    definition:'Excess Yelp reviews near a project per $1 million of reported cost over the two years after opening, after adjusting for growth.',
    formula:'(near post − near pre × comparison post ÷ comparison pre) ÷ cost in $M',
    caution:'This counts reviews. It says nothing about revenue, financial return or public benefit. Reported costs mix public and private scope inconsistently.'},
  ridge:{term:'Ridge regression',category:'model',
    definition:'Linear regression with an L2 penalty that shrinks coefficients toward zero, which steadies estimates when there are few observations. Our baseline predicts CE from budget, reviewed-business count and review intensity, each log-transformed and standardized, with penalty α = 10.',
    caution:'Fit to ten projects. Project type is not an input.'},
  holdout:{term:'Held-out evaluation',category:'model',
    definition:'We refit the model without one project, or without every project in one city, then score it on what was left out.',
    formula:'Baseline MAE is 49.3 reviews per $1M by project and 45.6 by city, against 61.6 and 58.5 for predicting the mean'},
  mae:{term:'Mean absolute error (MAE)',category:'model',
    definition:'The average size of prediction misses, ignoring direction. Lower is better.'},
  challengers:{term:'Challenger models',category:'model',
    definition:'Alternatives we tested against the baseline: sentiment and topic-share features, the pre-opening trend, and TF-IDF and NMF text features refit inside each validation fold. None improved both hold-out errors.'},
  error_envelope:{term:'Historical error envelope',category:'model',
    definition:'The point estimate plus or minus the largest city-held-out error observed.',
    caution:'Treat it as a rough band. It is not a calibrated confidence interval.'},

  zcta:{term:'ZIP / ZCTA',category:'geography',
    definition:'Census ZIP Code Tabulation Areas approximate postal ZIP codes with fixed polygons. Boundaries come from the Census TIGERweb service. We map 196 areas across five metros.'},
  acs:{term:'American Community Survey (ACS)',category:'geography',
    definition:'The Census Bureau\'s rolling household survey. Its five-year estimates give income and poverty for small areas, each with a margin of error.'},
  yelp:{term:'Yelp Open Dataset',category:'geography',
    definition:'Yelp\'s academic release of businesses and reviews, from a January 2022 archive. We scored 1,063,956 unique reviews around eleven projects in seven cities.',
    caution:'Covers only selected metros and Yelp-listed businesses. Used under the dataset\'s terms.'},
  agent_labels:{term:'Agent labels',category:'text',
    definition:'Labels for the 731-item validation sample, written by Claude Opus acting as an annotator. It saw only the review text, never the VADER or rule output, and followed our written codebook for target, topics and polarity.',
    caution:'No person has checked these yet. People will recheck them, and the accuracy figures may change.'},
  embedding_classifier:{term:'BERT-embedding classifier',category:'text',
    definition:'Logistic regression on all-MiniLM-L6-v2 sentence embeddings, trained on the agent labels with folds grouped by business. It found negative area comments far better than the keyword rules, with F1 0.52 against 0.23.',
    caution:'So far it has only been scored on the labeled sample. It has not rescored the full set of reviews.'}
};

export function glossaryEntries(){return Object.entries(GLOSSARY).map(([key,e])=>({key,...e}));}
