// Single source for term definitions: Place Lab modals and methods.html read the same entries.
// Keys are stable anchors (methods.html#term-<key>); edit wording here, not in either page.
export const CATEGORIES={
  measure:'ZIP measures',
  projection:'Project comparison',
  text:'Text analysis',
  model:'Modelling and evaluation',
  geography:'Geography and sources'
};

export const GLOSSARY={
  engagement:{term:'Business engagement',category:'measure',
    definition:'How actively people review local businesses in an area, measured as Yelp reviews per square kilometre per year. We use it as a proxy for customer engagement with nearby businesses.',
    formula:'Reviews in 2019–2021 ÷ 3 years ÷ ZIP area in km²',
    caution:'Counts written reviews, not visits, sales or revenue. Requires at least 100 reviews in the period. ZIP area includes water.'},
  engagement_change:{term:'Change in business engagement',category:'measure',
    definition:'Percentage change in the number of Yelp reviews between two equal three-year windows.',
    formula:'100 × (reviews 2019–2021 ÷ reviews 2012–2014 − 1)',
    caution:'Both windows need at least 100 reviews. The later window includes COVID-19. A change in reviews does not establish business openings or closures.'},
  listings:{term:'Yelp listings',category:'measure',
    definition:'Businesses in the Yelp Open Dataset whose coordinates fall in the ZIP.',
    caution:'An archive inventory (January 2022), not a census of all current businesses.'},
  reviews:{term:'Reviews',category:'measure',
    definition:'Count of Yelp reviews written for businesses in the ZIP during 2019–2021.'},
  sentiment:{term:'Average review sentiment',category:'measure',
    definition:'Mean VADER compound score of review text, from −1 (most negative) to +1 (most positive).',
    formula:'Sum of review compound scores ÷ number of reviews',
    caution:'Scores the whole review, which is usually about the business rather than the neighbourhood.'},
  sentiment_vs_metro:{term:'Sentiment change vs. rest of metro',category:'measure',
    definition:'How much the ZIP’s average sentiment changed between 2012–2014 and 2019–2021, relative to the change across the rest of its metro area.',
    formula:'(ZIP late − ZIP early) − (rest-of-metro late − rest-of-metro early)',
    caution:'A positive value can occur even when the ZIP’s own sentiment fell, if the metro fell further.'},
  access_discussion:{term:'Access & parking discussion',category:'measure',
    definition:'Share of 2019–2021 reviews that mention parking, walking, transit or accessibility.',
    formula:'100 × reviews with an access keyword ÷ all reviews',
    caution:'Includes praise as well as complaints. It is a discussion rate, not a complaint rate.'},
  income:{term:'Median household income',category:'measure',
    definition:'American Community Survey five-year estimate of median household income for the ZCTA, in nominal dollars, with its published margin of error.',
    caution:'2007–2011 for Philadelphia and Tucson; 2008–2012 for other metros. Describes residents, not Yelp reviewers.'},
  poverty:{term:'Population below poverty',category:'measure',
    definition:'ACS five-year estimate of the share of the poverty-status population below the federal poverty line.',
    caution:'Same baseline periods as income. Historical, not current conditions.'},
  area:{term:'Land and water area',category:'measure',
    definition:'Area of the ZIP Code Tabulation Area polygon on a sphere, with holes subtracted.',
    caution:'Includes water, which lowers per-km² engagement for waterfront ZIPs.'},
  city_median:{term:'City median',category:'measure',
    definition:'Middle value of the measure across all mapped ZIPs in the same metro that have data.'},
  city_rank:{term:'City rank',category:'measure',
    definition:'Position of the ZIP among mapped ZIPs in its metro, where 1 is the highest value. ZIPs with limited data are not ranked.'},
  limited_data:{term:'Limited data',category:'measure',
    definition:'The ZIP did not meet the minimum evidence rule for this measure (usually 100 reviews per period) or the source had no estimate.',
    caution:'Limited data is not zero.'},

  project_family:{term:'Project family',category:'projection',
    definition:'A grouping of historical projects by kind: trail / greenway, waterfront park, civic park / plaza, or transit line. The eleven source projects each had a unique type label, so we grouped them to compare like with like.'},
  near_area:{term:'Near area',category:'projection',
    definition:'Reviewed businesses within 500 metres of a historical project’s mapped footprint or centre point.'},
  comparison_area:{term:'Comparison area',category:'projection',
    definition:'Reviewed businesses between 1.5 and 8 km from the same project. It captures citywide trends that would have happened without the project.'},
  adjusted_change:{term:'Comparison-adjusted change',category:'projection',
    definition:'A difference-in-differences: the change near a project from two pre-opening years to two post-opening years, minus the same change in its comparison area.',
    formula:'(near post − near pre) − (comparison post − comparison pre)',
    caution:'Engagement is compared on a log scale, so it reads as a percentage difference in growth.'},
  family_average:{term:'Family average',category:'projection',
    definition:'The average comparison-adjusted change across the past projects of one kind (or all ten), with the number of projects that moved in the better direction. Engagement is averaged on a log scale, so it is a geometric mean of growth ratios.',
    caution:'A summary of what happened at a handful of places, not an expected effect. Family averages did not predict held-out projects better than the all-project average.'},
  range_in_family:{term:'Range in family',category:'projection',
    definition:'The lowest and highest comparison-adjusted change among the projects in the family. It shows how much projects of the same kind differed.'},
  negative_access:{term:'Negative access & parking mentions',category:'projection',
    definition:'Share of reviews with a clause that is negative about walking, transit or parking and refers to the surrounding area rather than the business.',
    caution:'Low reliability. Against 514 labelled clauses (agent labels pending human recheck), the keyword rules found about 1 in 6 negative area comments (recall 0.16, precision 0.39), so this rate undercounts complaints.'},
  negative_realm:{term:'Negative public-space mentions',category:'projection',
    definition:'Share of reviews with a negative clause about safety, cleanliness, public space, construction or the neighbourhood that refers to the surrounding area.',
    caution:'Low reliability, for the same reason as negative access mentions: the rules miss most negative area comments that a reader finds.'},
  loo_check:{term:'Leave-one-project-out check',category:'projection',
    definition:'Each project is removed in turn, its family estimate is recomputed from the others, and the miss is recorded. We compare that error with the error of the plain all-project average.',
    caution:'Family estimates did not beat the all-project average on any measure. Differences within families are larger than differences between them.'},

  vader:{term:'VADER',category:'text',
    definition:'Valence Aware Dictionary and sEntiment Reasoner: a lexicon- and rule-based sentiment scorer for short social-media text. It returns a compound score from −1 to +1 and handles negation, intensifiers and punctuation.',
    caution:'A lexical baseline, not a trained classifier. Applied with the vaderSentiment Python package.'},
  clause_rules:{term:'Clause-level topic rules',category:'text',
    definition:'Reviews are split into clauses. Keyword patterns tag nine topics (walking, transit, parking, safety, cleanliness, public space, construction, food/service, neighbourhood). Each clause is then labelled as about the area or the business, and as positive, neutral or negative using VADER plus explicit complaint phrases.',
    caution:'Versioned provisional rules (place-clause-rules-v1). 731 items are prepared for human annotation; precision and recall are not yet measured.'},
  tfidf:{term:'TF-IDF',category:'text',
    definition:'Term frequency–inverse document frequency: represents each review as weighted word and two-word-phrase counts, down-weighting words common to most reviews.',
    formula:'Unigrams and bigrams, sublinear term frequency, English stop words, min document frequency 2, max 95%, 8,000 features'},
  nmf:{term:'Non-negative matrix factorization (NMF)',category:'text',
    definition:'An unsupervised topic model that factors the TF-IDF matrix into five topics, each a weighted list of terms, and gives every review a mixture of those topics.',
    caution:'Fit to 10,971 sampled baseline reviews. Most learned topics describe food and service, not civic conditions.'},
  topic_diversity:{term:'Topic diversity',category:'text',
    definition:'Shannon entropy of a project’s average topic mixture, divided by log(5). Zero means one dominant topic; one means an even spread.'},

  capital_efficiency:{term:'Capital efficiency (CE)',category:'model',
    definition:'Growth-adjusted excess Yelp reviews near a project per $1 million of reported cost over two post-opening years.',
    formula:'(near post − near pre × comparison post ÷ comparison pre) ÷ cost in $M',
    caution:'Not revenue, financial return or public benefit. Reported costs have inconsistent public/private scope.'},
  ridge:{term:'Ridge regression',category:'model',
    definition:'Linear regression with an L2 penalty that shrinks coefficients toward zero, which stabilises estimates with few observations. Our baseline predicts CE from budget, reviewed-business count and review intensity, each log-transformed and standardised (penalty α = 10).',
    caution:'Fit to ten projects. Project type is not an input.'},
  holdout:{term:'Held-out evaluation',category:'model',
    definition:'The model is refit without one project (project hold-out) or without every project in one city (city hold-out), then scored on what was left out.',
    formula:'Baseline MAE: 49.3 (project) and 45.6 (city) reviews per $1M, against 61.6 and 58.5 for predicting the mean'},
  mae:{term:'Mean absolute error (MAE)',category:'model',
    definition:'The average size of prediction misses, ignoring direction. Lower is better.'},
  challengers:{term:'Challenger models',category:'model',
    definition:'Alternatives tested against the baseline: sentiment and topic-share features, pre-opening trend, and TF-IDF/NMF text features refit inside each validation fold. None improved both hold-out errors.'},
  error_envelope:{term:'Historical error envelope',category:'model',
    definition:'The point estimate plus or minus the largest city-held-out error observed.',
    caution:'Not a calibrated confidence interval.'},

  zcta:{term:'ZIP / ZCTA',category:'geography',
    definition:'Census ZIP Code Tabulation Areas approximate postal ZIP codes with fixed polygons. Boundaries come from the Census TIGERweb service; 196 areas are mapped across five metros.'},
  acs:{term:'American Community Survey (ACS)',category:'geography',
    definition:'The Census Bureau’s rolling household survey. Five-year estimates provide income and poverty for small areas, each with a margin of error.'},
  yelp:{term:'Yelp Open Dataset',category:'geography',
    definition:'Yelp’s academic release of businesses and reviews (January 2022 archive). We scored 1,063,956 unique reviews around eleven projects in seven cities.',
    caution:'Covers selected metros and Yelp-listed businesses only. Used under the dataset’s terms.'},
  agent_labels:{term:'Agent labels',category:'text',
    definition:'Labels for the 731-item validation sample produced by Claude Opus acting as an annotator. It saw only the review text, not VADER or rule output, and followed the written codebook for target, topics and polarity.',
    caution:'Not independent human validation. Humans will recheck them; the accuracy figures may change.'},
  embedding_classifier:{term:'BERT-embedding classifier',category:'text',
    definition:'Logistic regression on all-MiniLM-L6-v2 sentence embeddings, trained on the agent labels with folds grouped by business. It found negative area comments far better than the keyword rules (F1 0.52 vs 0.23).',
    caution:'Evaluated on the labelled sample only; it has not yet rescored the full review corpus.'}
};

export function glossaryEntries(){return Object.entries(GLOSSARY).map(([key,e])=>({key,...e}));}
